import Instructions from "../components/Instructions/CalcAllowed";
import Head from 'next/head'

const calcAllowedInstructions = () => {
    return (
        <>
        <Head>
            <title>EducationUSA Abuja SAT MockTest Site</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <body className="bg-gradient-to-r from-sky-400 to-blue-400">

        <Instructions/>
        </body>
        </>
    );
}

export default calcAllowedInstructions;