import FullExam from '../components/Exam/FullExam'
import Head from 'next/head'

const reading = () => {
    return (
        <>
            <Head>
                <title>EducationUSA Abuja SAT MockTest Site</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FullExam/>
        </>
    );
        
}

export default reading;